# Generated by Django 3.0.3 on 2020-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='logo_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
