# Generated by Django 3.0.3 on 2020-03-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockerapp', '0002_auto_20200306_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='portfolio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stockerapp.Portfolio'),
            preserve_default=False,
        ),
    ]
